venv_design_search/design_search/design_search/urls.py
from django.urls import path
from . import views
# from .views import email_form
from .views import inquiry_list

from django.conf import settings
from django.conf.urls.static import static
from .views import EditInquiryView
from .views import DetailInquiryView


app_name = 'design_search'
urlpatterns = [
    path('diary/', views.DiaryView.as_view(), name="diary"),
    path('hello/', views.HelloView.as_view(), name="hello"),
    path('tashizan/', views.TashizanView.as_view(), name="tashizan"),
    path('kajiki/', views.KajikiView.as_view(), name="kajiki"),
    path('tenki/', views.TenkiView.as_view(), name="tenki"),
    path('tashizan_form/', views.TashizanFormView, name="tashizan_form"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('inquiry_list/', inquiry_list, name='inquiry_list'),
    path('edit_inquiry/<int:inquiry_id>/', EditInquiryView.as_view(), name='edit_inquiry'),
    path('detail_inquiry/<int:inquiry_id>/', DetailInquiryView.as_view(), name='detail_inquiry'),
    # path('email/', views.email_form, name='email_form'),
    path('hantei/', views.HanteiView.as_view(), name="hantei"),
]

# 開発環境でのみメディアファイルを提供する設定を追加
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

venv_design_search/design_search/design_search_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('design_search.urls')),
]

venv_design_search/design_search/design_search/forms.py
import os

from django import forms
from django.core.mail import EmailMessage
from .models import Inquiry


class InquiryForm(forms.ModelForm):
    POSSIBILITY_CHOICES = [
        ('採用', '採用'),
        ('不採用', '不採用'),
    ]
    REUSE_CHOICES = [
        ('未', '未'),
        ('済', '済'),
    ]
    GENRE_CHOICES = [
        ('シンプル', 'シンプル'),
        ('イラストレーション', 'イラストレーション'),
        ('写真重視', '写真重視'),
        ('レトロ', 'レトロ'),
        ('カラフル', 'カラフル'),
        ('情報重視', '情報重視'),
        ('タイポグラフィ', 'タイポグラフィ'),
    ]

    possibility = forms.ChoiceField(label='採用の可否', choices=POSSIBILITY_CHOICES, required=False)
    reuse = forms.ChoiceField(label='再利用', choices=REUSE_CHOICES, required=False)

    # チェックボックスのフィールドを追加
    genres = forms.MultipleChoiceField(
        label='デザインの種類',
        choices=GENRE_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Inquiry
        exclude = ['created_at']  # created_at を除外
        fields = '__all__'

    # カスタムのバリデーションやウィジェットの設定が必要な場合はここに追加
    widgets = {
        'genres': forms.Select(choices=GENRE_CHOICES),
    }



    pdf_file = forms.FileField(label='PDFファイル', required=False)

    shiji_no = forms.CharField(label='指示書No', max_length=6)
    shiji_name = forms.CharField(label='品名', max_length=99, required=False)
    name = forms.CharField(label='制作者', max_length=30)
    email = forms.EmailField(label='メールアドレス', required=False)
    purpose = forms.CharField(label='用途', max_length=99)
    message = forms.CharField(label='備考', widget=forms.Textarea, required=False)
    design_image = forms.ImageField(label='デザイン画像', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = " " #ラベルの末尾につくコロンを消す

        self.fields['shiji_no'].widget.attrs['class'] = 'form-control'
        self.fields['shiji_no'].widget.attrs['placeholder'] = '指示書Noをここに入力してください。'

        self.fields['shiji_name'].widget.attrs['class'] = 'form-control'
        self.fields['shiji_name'].widget.attrs['placeholder'] = '品名をここに入力してください。'

        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = '制作者をここに入力してください。'

        self.fields['possibility'].widget.attrs['class'] = 'form-select'

        self.fields['reuse'].widget.attrs['class'] = 'form-select'

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['purpose'].widget.attrs['class'] = 'form-control'
        self.fields['purpose'].widget.attrs['placeholder'] = '用途をここに入力してください。（例：Webサイト）'

        self.fields['message'].widget.attrs['class'] = 'form-control'
        self.fields['message'].widget.attrs['placeholder'] = '備考をここに入力してください。'
        self.fields['message'].widget.attrs['rows'] = 3

        self.fields['design_image'].widget.attrs['class'] = 'form-control'

        self.fields['pdf_file'].widget.attrs['class'] = 'form-control'
        self.fields['pdf_file'].widget.attrs['accept'] = '.pdf'

    # 既存のフォームセットに新しいフィールドを追加
    def clean(self):
        cleaned_data = super().clean()
        design_image = cleaned_data.get('design_image')
        pdf_file = cleaned_data.get('pdf_file')
        genres = cleaned_data.get('genres')

        # どちらかのファイルがアップロードされていることを確認
        if not design_image and not pdf_file:
            raise forms.ValidationError("デザイン画像またはPDFファイルのいずれかをアップロードしてください。")

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        purpose = self.cleaned_data['purpose']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(name)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = os.environ.get('FROM_EMAIL')
        to_list = [
            os.environ.get('FROM_EMAIL')
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()





# views.py

from django.shortcuts import render, get_object_or_404
from django.views import View  # Viewを追加
from django.core.mail import EmailMessage
from django.http import HttpResponseRedirect
from .models import Inquiry
from .forms import InquiryForm

class EditInquiryView(View):
    template_name = 'edit_inquiry.html'

    def get(self, request, inquiry_id):
        inquiry = get_object_or_404(Inquiry, id=inquiry_id)
        form = InquiryForm(instance=inquiry)
        # genresのchoicesを指定
        form.fields['genres'].widget.choices = InquiryForm.GENRE_CHOICES
        return render(request, self.template_name, {'form': form, 'inquiry': inquiry})




class EditInquiryForm(forms.ModelForm):
    # 他のフィールドの定義...

    genres = forms.MultipleChoiceField(
        choices=[('シンプル', 'シンプル'), ('イラストレーション', 'イラストレーション'), ...],
        widget=forms.CheckboxSelectMultiple,
        required=False  # 必要に応じて変更
    )

    class Meta:
        model = Inquiry  # 適切なモデルに変更
        fields = '__all__'









# forms.py に追加
class InquirySearchForm(forms.Form):
    # 他のフィールド...
    genres = forms.CharField(label='デザインの種類', required=False)

venv_design_search/design_search/design_search/views.py
import logging
from django.views import generic
from django.views.generic import ListView
from .models import Post
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from .models import EmailModel  # EmailModelはデータベースモデルとして作成しておく
from .models import Inquiry
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from .forms import InquiryForm
from django.shortcuts import get_object_or_404, render
from django.views import View



logger = logging.getLogger(__name__)


def index(request):
    if request.method == 'POST':
        form = InquiryForm(request.POST, request.FILES)
        if form.is_valid():
            form.send_email()
            form.save()
            return HttpResponseRedirect('/thanks/')
    else:
        form = InquiryForm()

    return render(request, 'index.html', {'form': form})



class DiaryView(generic.TemplateView):
    template_name = "diary.html"

class HelloView(generic.TemplateView):
    template_name = "hello.html"

class TashizanView(generic.ListView):
    model = Post
    template_name = 'tashizan.html'
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['names'] = '川上'
        value = 10 + 20
        context['value'] = value
        a = 7
        b = 5
        c = 10
        context['tashizan'] = a + b + c
        return context

class KajikiView(generic.TemplateView):
    model = Post
    template_name = "kajiki.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        import requests
        from bs4 import BeautifulSoup
        import re
        import os.path
        
        url = "https://www.kajiki-k.jp/" # 読み込み先のURL
        res = requests.get(url)
        res.encoding = 'UTF-8' # エンコーディングを適切な値に設定する
        
        soup = BeautifulSoup(res.text, "html.parser")
        elems = soup.find_all(href=re.compile("diary/2023")) # Topページの「diary/2023」というテキストが含まれた要素を探す
        toppage_links = [elem.attrs['href'] for elem in elems] # Topページの「diary/2023」というaタグの中身を取得
        
        toppage_links_lists =[] # Topページの「diary/2023」というaタグの中身を単体ではなく複数取得して変数に入れる為にリストを作成
        for toppage_link in toppage_links:
            toppage_links_lists.append(toppage_link.replace('diary/', 'https://www.kajiki-k.jp/diary/')) # toppage_links_listsに.appendを使ってリストに要素を追加する。その際に「diary/」を「https://www.kajiki-k.jp/diary/」に置換する。置換する意味は絶対パスにして次のプログラミングでその絶対パスのリンク先に移動する為。
        
        # 複数取得して変数に入れる為にリストを作成
        result_title = []
        result_link = []
        result_h3text = []
        result_divtext = []
        kugiri = "\n--------------------\n"
        
        # Topで取得した「https://www.kajiki-k.jp/diary/2023/diary23○○.html」の複数のページへそれぞれ移動し順に処理
        for toppage_links_list in toppage_links_lists:
            toppage_links_lists_res = requests.get(toppage_links_list)
            toppage_links_lists_res.encoding = 'UTF-8'  # エンコーディングを適切な値に設定する
            toppage_links_lists_soup = BeautifulSoup(toppage_links_lists_res.text, "html.parser")
        
             # ページタイトルを複数取得し、変数result_titleのリストへ格納
            result_title.append(toppage_links_lists_soup.title.text + kugiri)
            # print(toppage_links_lists_soup.title.text)
        
             # URLを複数取得し、変数result_linkのリストへ格納
            result_link.append(toppage_links_list + kugiri)
            # print(toppage_links_list)
        
            h3texts = toppage_links_lists_soup.find_all("h3", class_="diary_title") # h3タグの.diary_titleを取得
            for h3text in h3texts:
                result_h3text.append(h3text.get_text() + kugiri) # .diary_titleを複数取得し、変数result_h3textのリストへ格納
                # print(h3text.get_text())
        
            divtexts = toppage_links_lists_soup.find_all("div", class_="update_contents_right_box_in") #divタグの.update_contents_right_box_inを取得
            for divtext in divtexts:
                result_divtext.append(divtext.get_text() + kugiri) # .update_contents_right_box_inを複数取得し、変数result_divtextのリストへ格納
                # print(divtext.get_text())
        
            # リストの要素を.joinを使って、スペース区切りで結合した文字列にする。テキストファイルに書き出すにはリストのままでは不可なので、str（文字列）にする必要がある為。
            result_title_str = ' '.join(result_title)
            result_link_str = ' '.join(result_link)
            result_h3text_str = ' '.join(result_h3text)
            result_divtext_str = ' '.join(result_divtext)
        
            dirname = os.path.dirname(__file__)
            path = os.path.join(dirname, "templates/kajiki_croll.txt")
            f = open(path, "w", encoding="utf-8") # テキストファイルを開く。保存場所を指定しないとユーザーフォルダ直下にデフォルトでは出来てしまう為、保存場所を指定。wなのでまっさらにして書き込む。
            f.write(result_title_str + result_link_str + result_h3text_str + result_divtext_str) # テキストファイルに書き込む
            f.close() # テキストファイルを閉じる

        context['kajiki1'] = result_title_str
        context['kajiki2'] = result_link_str
        context['kajiki3'] = result_h3text_str
        context['kajiki4'] = result_divtext_str
        return context

class TenkiView(generic.ListView):
    model = Post
    template_name = "tenki.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        import requests
        from bs4 import BeautifulSoup
        import pandas as pd
        
        def GET_Weather():
            # 大阪市淀川区の天気のURLをセット
            url = "https://tenki.jp/forecast/6/30/6200/27123/"
            r = requests.get(url)
            soup = BeautifulSoup(r.text, "html.parser")
            rs = soup.find(class_='forecast-days-wrap clearfix')
            # 天気を取得
            rs_wether = rs.findAll(class_='weather-telop')
            today_weather = rs_wether[0].text.strip()
            tomorrow_weather = rs_wether[1].text.strip()
            # 最高気温を取得
            rs_hightemp = rs.findAll(class_='high-temp temp')
            today_hightemp = rs_hightemp[0].text.strip()
            tomorrow_hightemp = rs_hightemp[1].text.strip()
            # 最高気温差を取得
            rs_hightempdiff = rs.findAll(class_='high-temp tempdiff')
            today_hightempdiff = rs_hightempdiff[0].text.strip()
            tomorrow_hightempdiff = rs_hightempdiff[1].text.strip()
            # 最低気温を取得
            rs_lowtemp = rs.findAll(class_='low-temp temp')
            today_lowtemp = rs_lowtemp[0].text.strip()
            tomorrow_lowtemp = rs_lowtemp[1].text.strip()
            # 最高気温差を取得
            rs_lowtempdiff = rs.findAll(class_='low-temp tempdiff')
            today_lowtempdiff = rs_lowtempdiff[0].text.strip()
            tomorrow_lowtempdiff = rs_lowtempdiff[1].text.strip()
            # 降水確率を取得
            rs_rain = soup.select('.rain-probability > td')
            today_rain_1 = rs_rain[0].text.strip()
            today_rain_2 = rs_rain[1].text.strip()
            today_rain_3 = rs_rain[2].text.strip()
            today_rain_4 = rs_rain[3].text.strip()
            tomorrow_rain_1 = rs_rain[4].text.strip()
            tomorrow_rain_2 = rs_rain[5].text.strip()
            tomorrow_rain_3 = rs_rain[6].text.strip()
            tomorrow_rain_4 = rs_rain[7].text.strip()
            # 風向
            rs_wind = soup.select('.wind-wave > td')
            print(rs_wind)
            today_wind = rs_wind[0].text.strip()
            tomorrow_wind = rs_wind[1].text.strip()
            # 取得結果をdfに格納
            # df = pd.DataFrame(
            # data={'#': ['天気', '最高気温', '最高気温差', '最低気温', '最低気温差', 
            #         '降水確率[00-06]', '降水確率[06-12]', '降水確率[12-18]', 
            #         '降水確率[18-24]', '風向'],
            #       '今日': [today_weather, today_hightemp, today_hightempdiff, 
            #         today_lowtemp, today_lowtempdiff, today_rain_1, today_rain_2, 
            #         today_rain_3, today_rain_4, today_wind], 
            #       '明日': [tomorrow_weather, tomorrow_hightemp, tomorrow_hightempdiff, 
            #         tomorrow_lowtemp, tomorrow_lowtempdiff, tomorrow_rain_1, tomorrow_rain_2, 
            #         tomorrow_rain_3, tomorrow_rain_4, tomorrow_wind],
            #     }
            # )
            # print(df)
            context['templates_weather1'] = '天気：' + today_weather + "\n最高気温：" + today_hightemp + '\n最高気温差：' + today_hightempdiff + '\n最低気温差：' + today_lowtemp + '\n降水確率[00-06]：' + today_rain_1 + '\n降水確率[06-12]：' + today_rain_2 + '\n降水確率[12-18]：' + today_rain_3 + '\n降水確率[18-24]：' + today_rain_4 + '\n風向：' + today_wind
            
            context['templates_weather2'] = '天気：' + tomorrow_weather + "\n最高気温：" + tomorrow_hightemp + '\n最高気温差：' + tomorrow_hightempdiff + '\n最低気温差：' + tomorrow_lowtemp + '\n降水確率[00-06]：' + tomorrow_rain_1 + '\n降水確率[06-12]：' + tomorrow_rain_2 + '\n降水確率[12-18]：' + tomorrow_rain_3 + '\n降水確率[18-24]：' + tomorrow_rain_4 + '\n風向：' + tomorrow_wind
        GET_Weather()

        return context

def TashizanFormView(request):
    template_name="tashizan_form.html"
    context = {}  # コンテキスト辞書を初期化

    if request.POST:
        numbers1 = int(request.POST['numbers1'])
        numbers2 = int(request.POST['numbers2'])

    #受け取った値で必要な処理を行います
        context['numbers1'] = numbers1  # コンテキストに変数を追加
        context['numbers2'] = numbers2  # コンテキストに変数を追加
        context['result'] = numbers1 + numbers2

    return render(request, template_name, context)  # コンテキストをテンプレートに渡す)

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('design_search:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, '登録しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))

        # データベースに保存
        form.save()

        return super().form_valid(form)


from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render

venv_design_search/design_search/design_search/templates/edit_inquiry.html
<!-- edit_inquiry.html -->

{% extends 'base1.html' %}

{% block title %}編集 | Design Management System{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}

      <div class="white-box">
        <!-- <h1 class="display-5">編集</h1> -->
  
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}

          {{ form.non_field_errors }}
			
          {% for field in form %}
          <div class="mb-4">
            <label for="{{ field.id_for_label }}" class="form-label">
              <strong>{{ field.label }}</strong>
              {% if field.field.required %}<span class="required-mark">*</span>{% endif %}
            </label>
            {{ field }}
            {{ field.errors }}
          </div>
          {% endfor %}
  
          <div class="text-center mt-5">
            <button class="btn btn-primary btn-lg rounded-pill submit-btn px-5 py-3" type="submit">保存する</button>
          </div>
        </form>
      </div>

{% endblock %}

venv_design_search/design_search/design_search/templates/hantei.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>判定</title>
  </head>

  <body>
    <h1>判定</h1>
    <p>{{hantei1}}</p>
    <p style="margin-bottom: 30px;">{{hantei2}}</p>
    <p>「hantei」フォルダの中に入っている「test.jpg」は</p>
    <p style="color: red; font-weight: bold; font-size: 32px;">{{hantei3}}</p>
    <p>の画像です。</p>
  </body>
</html>

venv_design_search/design_search/design_search/templates/inquiry_list.html
{% extends 'base1.html' %}

{% block title %}Design Management System{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
    <div id="loader-wrap">
        <div class="loader"></div>
    </div>

    <div class="">
        <div class="curved">
            <form method="get" action="" class="search-form">
                <div class="input-group input-group-sm me-3">
                    <label for="searchColumn" class="input-group-text">検索列</label>
                    <select id="searchColumn" class="form-select" name="search_column" >
                        <option value="all" {% if search_column == 'all' %}selected{% endif %}>全て</option>
                        <option value="shiji_no" {% if search_column == 'shiji_no' %}selected{% endif %}>指示書No</option>
                        <option value="shiji_name" {% if search_column == 'shiji_name' %}selected{% endif %}>品名</option>
                        <option value="name" {% if search_column == 'name' %}selected{% endif %}>制作者</option>
                        <option value="possibility" {% if search_column == 'possibility' %}selected{% endif %}>採用の可否</option>
                        <option value="reuse" {% if search_column == 'reuse' %}selected{% endif %}>再利用</option>
                        <option value="email" {% if search_column == 'email' %}selected{% endif %}>メールアドレス</option>
                        <option value="purpose" {% if search_column == 'purpose' %}selected{% endif %}>用途</option>
                        <option value="message" {% if search_column == 'message' %}selected{% endif %}>備考</option>
                    </select>
                </div>

                <div class="input-group input-group-sm me-3">
                    <label for="searchText" class="input-group-text">検索するテキスト</label>
                    <input type="text" id="searchText" class="form-control" name="search_text" value="{{ search_text }}">
                </div>

                <div class="input-group input-group-sm me-3">
                    <label for="searchGenres" class="input-group-text">デザインの種類</label>
                    <select id="searchGenres" class="form-select" name="search_genres">
                        <option value="" {% if not search_genres %}selected{% endif %}>全て</option>
                        <option value="シンプル" {% if search_genres == 'シンプル' %}selected{% endif %}>シンプル</option>
                        <option value="イラストレーション" {% if search_genres == 'イラストレーション' %}selected{% endif %}>イラストレーション</option>
                        <option value="写真重視" {% if search_genres == '写真重視' %}selected{% endif %}>写真重視</option>
                        <option value="レトロ" {% if search_genres == 'レトロ' %}selected{% endif %}>レトロ</option>
                        <option value="カラフル" {% if search_genres == 'カラフル' %}selected{% endif %}>カラフル</option>
                        <option value="情報重視" {% if search_genres == '情報重視' %}selected{% endif %}>情報重視</option>
                        <option value="タイポグラフィ" {% if search_genres == 'タイポグラフィ' %}selected{% endif %}>タイポグラフィ</option>
                    </select>
                </div>

                <button type="submit" class="col-auto btn btn-sm search-btn">検索</button>
            </form>
        </div>
        
        <div class="bg-white pt-4 pb-5 mb-5">
            <div style="max-width: 1480px; margin: 0 auto;">
                <table class="table table-striped mt-0">
                    <thead>
                        <tr>
                            <th>詳細</th>
                            <th>投稿日時</th>
                            <th>指示書No</th>
                            <th>品名</th>
                            <th>制作者</th>
                            <th>採用の可否</th>
                            <th>再利用</th>
                            <th>メールアドレス</th>
                            <th>用途</th>
                            <th>備考</th>
                            <th>デザイン画像</th>
                            <th>PDFファイル</th>
                            <th>デザインの種類</th>
                            <th>編集</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for inquiry in inquiries %}
                            <tr>
                                <td>
                                    <a href="{% url 'design_search:detail_inquiry' inquiry.id %}">
                                        <span class="material-symbols-outlined" data-bs-toggle="tooltip" title="詳細を表示する">description</span>
                                    </a>
                                </td>
                                <td>{{ inquiry.created_at }}</td>
                                <td>{{ inquiry.shiji_no }}</td>
                                <td>{{ inquiry.shiji_name }}</td>
                                <td>{{ inquiry.name }}</td>
                                <td>{{ inquiry.possibility }}</td>
                                <td>{{ inquiry.reuse }}</td>
                                <td>{{ inquiry.email }}</td>
                                <td>{{ inquiry.purpose }}</td>
                                <td>{{ inquiry.message }}</td>
                                <td>
                                    {% if inquiry.design_image %}
                                        <a href="{{ inquiry.design_image.url }}" target="_blank" class="list-design-image"><img src="{{ inquiry.design_image.url }}" alt="Design Image"></a>
                                    {% else %}
                                        No Image
                                    {% endif %}
                                </td>
                                <td>
                                    {% if inquiry.pdf_file %}
                                        <a href="{{ inquiry.pdf_file.url }}" target="_blank"><img class="pdf_icon" src="../../static/template_pattern1/assets/img/pdf_icon.png" alt=""></a>
                                    {% else %}
                                        No PDF
                                    {% endif %}
                                </td>
                                <td>
                                    {% if inquiry.genres %}
                                    {{ inquiry.genres }}
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'design_search:edit_inquiry' inquiry.id %}">
                                        <span class="material-symbols-outlined" data-bs-toggle="tooltip" title="編集する">stylus</span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
            
            <div class="pagination-wrap mt-5">
                {% if inquiries.has_previous %}
                    <a href="?page=1{% if search_column %}&search_column={{ search_column }}{% endif %}{% if search_text %}&search_text={{ search_text }}{% endif %}" class="me-3"><span class="material-symbols-outlined" data-bs-toggle="tooltip" title="最初のページへ">first_page</span></a>
                    <a href="?page={{ inquiries.previous_page_number }}{% if search_column %}&search_column={{ search_column }}{% endif %}{% if search_text %}&search_text={{ search_text }}{% endif %}" class="me-3"><span class="material-symbols-outlined" data-bs-toggle="tooltip" title="前のページへ">chevron_left</span></a>
                {% else %}
                    <span class="is-disabled me-3"><span class="material-symbols-outlined">first_page</span></span>
                    <span class="is-disabled me-3"><span class="material-symbols-outlined">chevron_left</span></span>
                {% endif %}

                <span class="me-3">
                    {{ inquiries.number }} / {{ inquiries.paginator.num_pages }}
                </span>

                {% if inquiries.has_next %}
                    <a href="?page={{ inquiries.next_page_number }}{% if search_column %}&search_column={{ search_column }}{% endif %}{% if search_text %}&search_text={{ search_text }}{% endif %}" class="me-3"><span class="material-symbols-outlined" data-bs-toggle="tooltip" title="次のページへ">chevron_right</span></a>
                    <a href="?page={{ inquiries.paginator.num_pages }}{% if search_column %}&search_column={{ search_column }}{% endif %}{% if search_text %}&search_text={{ search_text }}{% endif %}"><span class="material-symbols-outlined" data-bs-toggle="tooltip" title="最後のページへ">last_page</span></a>
                {% else %}
                    <span class="is-disabled me-3"><span class="material-symbols-outlined">chevron_right</span></span>
                    <span class="is-disabled"><span class="material-symbols-outlined">last_page</span></span>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

venv_design_search/design_search/design_search/templates/kajiki.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>加治木議員</title>
  </head>

  <body>
    <h1>加治木議員</h1>
    <p>{{kajiki1}}</p>
    <p>{{kajiki2}}</p>
    <p>{{kajiki3}}</p>
    <p>{{kajiki4}}</p>
  </body>
</html>

venv_design_search/design_search/design_search/templates/tashizan.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>足し算</title>
  </head>

  <body>
    <h1>足し算</h1>
    <p>{{names}}</p>
    <p>{{value}}</p>
    <p>{{tashizan}}</p>
  </body>
</html>